- .gitmodules
- README.md
I think it might be a good idea to use [git submodules](https://git-scm.com/book/en/v2/Git-Tools-Submodules) for installing and updating the *pyjsgf* and *sphinxwrapper* dependencies, seeing as I haven't distributed them yet and I frequently update *pyjsgf* to fix bugs.
I think the instructions for installing using submodules are a bit tedious though. Perhaps something inside `setup.py` that installs using the submodules (if they've been set up) would be better.
> Submodules for some dependencies

- .gitignore
- dragonfly/actions/keyboard.py
Thanks go to @Milchshakee - [Monospark/dragonfire fork](https://github.com/Monospark/dragonfire)
Resolves #16.
> Add support for different keyboard layouts

- dragonfly/actions/action_paste.py
- dragonfly/windows/clipboard.py
Just a few lines to make it work with Unicode. I noticed  #15, but this change is small enough to make no obstacle for that
> Fix Paste action for Unicode

- dragonfly/grammar/grammar_base.py
> Fixed bug where newly-constructed rules were not inactivated.

- README.rst
- documentation/accessibility.txt
- documentation/miscellaneous.txt
- documentation/requirements.txt
- dragonfly/__init__.py
- dragonfly/accessibility/__init__.py
- dragonfly/accessibility/base.py
- dragonfly/accessibility/controller.py
- dragonfly/accessibility/ia2.py
- dragonfly/accessibility/utils.py
- dragonfly/log.py
- dragonfly/test/suites.py
- dragonfly/test/test_accessibility.py
- setup.py
Currently only Windows is supported, but the design supports multiple operating systems and APIs. This enables text selection and editing more powerful than what Dragon provides natively, to a wider range of applications (notably Chrome and Firefox).
> Add accessibility API support to Dragonfly. 

- dragonfly/actions/action_cmd.py
@LexiconCode I've made the changes to `RunCommand` we discussed a while ago. Mainly the option to run commands either synchronously or asynchronously. Let me know what you think :-)
> Update RunCommand action and documentation

- .gitignore
- CONTRIBUTING.rst
- documentation/engines.txt
- dragonfly/engines/backend_sapi5/__init__.py
- dragonfly/engines/backend_sapi5/engine.py
(gitignore: .idea was duplicated)
> Add WSR/SAPI5 retain audio support; tweak documentation & gitignore

- dragonfly/actions/action_function.py
The new argument allows using extras with different names than the function argument names. A usage example/doctest has been added to the action's documentation. This is compatible with the 'defaults'
argument. This gets around the `Function` action's limitation with positional/unknown arguments.
```Python
from dragonfly import Function
def func(x, y, z):
print("x: %d" % x)
print("y: %d" % y)
print("z: %d" % z)
action = Function(func, dict(n="x", m="y"), z=4)
action.execute({"n": 2, "m": 3})
```
This also fixes some print statements in the Function action doctests and changes a relative import so that the doctests run correctly.
@alexboche This is the change to `Function` that we discussed. Let me know if you see any problems :-)
> Add optional 'remap_data' argument to the Function action

- CHANGELOG.rst
- dragonfly/language/en/number.py
- dragonfly/test/test_language_en_number.py
issue https://github.com/dictation-toolbox/dragonfly/issues/84
> Accept "too" and "to" as equivalent to "two" for English Integers

- documentation/kaldi_engine.txt
- dragonfly/engines/backend_kaldi/audio.py
- dragonfly/engines/backend_kaldi/compiler.py
- dragonfly/engines/backend_kaldi/engine.py
- setup.py
> Kaldi v0.5.0: User Lexicon! Compilation Optimizations! Better Model!

- dragonfly/engines/backend_kaldi/compiler.py
- dragonfly/engines/backend_kaldi/engine.py
- dragonfly/log.py
- setup.py
Many big fixes and optimizations to get Caster running.
> Update Kaldi backend to 0.6

- documentation/kaldi_engine.txt
thanks @shervinemami for portaudio tip
> Improve Kaldi documentation

- dragonfly/parser.py
> Optimize parser logging

- documentation/accessibility.txt
- dragonfly/accessibility/__init__.py
- dragonfly/accessibility/atspi.py
- dragonfly/accessibility/ia2.py
I've successfully tested this on Linux using my Google API integration (which I still haven't cleaned up and committed upstream ... but it looks like things have moved well beyond that with the Kaldi integration). It's very similar to the Windows integration; just various name and interface changes here and there.
> Implemented alpha support for accessibility API on Linux.

- documentation/kaldi_engine.txt
- dragonfly/engines/backend_kaldi/audio.py
- dragonfly/engines/backend_kaldi/compiler.py
- dragonfly/engines/backend_kaldi/engine.py
- dragonfly/examples/kaldi_module_loader.py
- dragonfly/examples/kaldi_module_loader_plus.py
- dragonfly/test/test_engine_kaldi.py
- setup.py
* **Partial Decoding**: support for having **separate Voice Activity Detection timeout values** based on whether the current utterance is complex (dictation) or not.
* **Parallel Compilation**: when compiling grammars/rules that are not cached, multiple can be compiled at once (up to your core count).
* Example: loading Caster without cache is ~40% faster (in addition to optimizations below).
* **Various Optimizations**: loading even while cached sped up 15%.
* Refactored temporary/cache file handling
* Various bug fixes
> KaldiAG v0.7.1: Partial Decoding, Parallel Compilation, & Various Optimizations for 15-50% Speedup

- documentation/kaldi_engine.txt
- dragonfly/__init__.py
- dragonfly/engines/backend_kaldi/compiler.py
- dragonfly/engines/backend_kaldi/engine.py
- dragonfly/test/test_engine_kaldi.py
- setup.py
This should resolve all current issues, hopefully. There is one oddity that I haven't been able to consistently reproduce with cloud dictation, but I don't think that is used much currently anyway, and it is mostly working.
> Kaldi Updates

- dragonfly/engines/backend_natlink/engine.py
I think this fixes https://github.com/dictation-toolbox/dragonfly/issues/144 I haven't tested fully, but the castor examples seem to be working well, now.
> Don't choke on Canadian English

- dragonfly/engines/backend_natlink/engine.py
Somewhat related to #144.
The `_get_language()` method will now check for best matches using the primary language identifier if there isn't an exact match in the _language_tags dictionary.
What this means is that language variants not explicitly listed in `_language_tags` should still work. For instance, Malaysian English (`0x4409`), if Dragon is actually sold there (no idea), will be identified as English (`0xXX09`) and `engine.language` will yield `"en"` as normal without raising an error.
For reference, Dragonfly gets a Windows language identifier from Dragon in this method. The relevant Microsoft Docs page for those is [this one](https://docs.microsoft.com/en-us/windows/win32/intl/language-identifier-constants-and-strings), which contains a long list of languages, their identifiers, …
> Improve the Natlink engine's language tag matching code

- dragonfly/engines/backend_natlink/__init__.py
- dragonfly/engines/backend_natlink/engine.py
This is shamefully completely untested, as I don't have DNS installed currently, but it looks right to me. It may be helpful for folks looking to prepare a data set for training another engine. Thanks to @dwks for the initial code.
> Add Natlink retain support

- dragonfly/engines/backend_kaldi/engine.py
Should fix (part of) https://github.com/daanzu/kaldi-active-grammar/issues/3 and https://github.com/mrob95/Breathe/issues/1 . @mrob95
> Fix Kaldi support for adding grammars during process_begin() callbacks

- dragonfly/actions/action_focuswindow.py
Has been helpful for me for a long time. Only recently integrated into upstream.
> Add FocusWindow options to select by index, or filter by passed func

- dragonfly/engines/backend_natlink/engine.py
- dragonfly/engines/backend_sapi5/engine.py
- dragonfly/engines/backend_sphinx/engine.py
- dragonfly/engines/backend_sphinx/grammar_wrapper.py
- dragonfly/test/suites.py
- dragonfly/test/test_contexts.py
This PR includes a few miscellaneous fixes to the engine backends and test suites.
> Misc engine and test suite fixes

- documentation/recobs.txt
- documentation/test_recobs_doctest.txt
- dragonfly/__init__.py
- dragonfly/engines/backend_kaldi/engine.py
- dragonfly/engines/backend_natlink/engine.py
- dragonfly/engines/backend_natlink/recobs.py
- dragonfly/engines/backend_sapi5/engine.py
- dragonfly/engines/backend_sphinx/engine.py
- dragonfly/engines/backend_sphinx/grammar_wrapper.py
- dragonfly/engines/backend_text/engine.py
- dragonfly/engines/base/engine.py
- dragonfly/engines/base/recobs.py
- dragonfly/grammar/recobs.py
- dragonfly/grammar/recobs_callbacks.py
@Danesprite Needs work on the natlink & sphinx backends.
And probably general look over and testing.
> Add new recognition observers: on_end() and on_post_recognition()

- documentation/test_word_formatting_v11_doctest.txt
- dragonfly/engines/backend_natlink/dictation_format.py
- dragonfly/engines/backend_natlink/engine.py
These are the simple ones, there are some more complex failures which I haven't really looked into yet.
> Some fixes for the natlink engine and its tests under py3

- dragonfly/actions/keyboard/_x11_xdotool.py
- dragonfly/windows/x11_window.py
> Fork sub-processes used by the X11 Keyboard and Window classes

- documentation/rules.txt
- dragonfly/__init__.py
- dragonfly/grammar/rule_basic.py
Re: #142 
@mrob95 I've implemented `BasicRule` based on your code in Breathe. Sorry it took me so long!
> Add BasicRule class for defining commands using elements directly

- dragonfly/grammar/rule_basic.py
- dragonfly/test/suites.py
- dragonfly/test/test_basic_rule.py
Fixes #274.
This also adds the unit tests I should have written in the first place. 😉
> Fix bug with BasicRule where it can only be used as a derived class

- documentation/test_grammar_elements_basic_doctest.txt
- dragonfly/grammar/elements_basic.py
> fix Repetition max inaccuracy

- dragonfly/grammar/context.py
Small improvement to be able to better debug FuncContexts.
> Improve debug logging for FuncContext

- dragonfly/engines/backend_sapi5/engine.py
Processing window title changes as well as foreground window changes allows title-based grammar/rule contexts to work responsively with the SAPI5 engine back-end.
> Change SAPI5 WinEvent hook to process window title changes too

- dragonfly/actions/action_context.py
Re: #301.
This includes validation checks of the actions list, ensuring it is dictionary-like list of context-action pairs, as well as a type check for the default action.
> Add validation and type checks into the ContextAction class

- documentation/test_grammar_list_doctest.txt
- dragonfly/grammar/elements_basic.py
- dragonfly/grammar/grammar_base.py
- dragonfly/grammar/rule_base.py
See my comment below for summary of the changes and other relevant info.
> Grammar sub-package changes

- dragonfly/__main__.py
This allows setting all of the available engine parameter options for Kaldi, which currently isn't possible for non-string parameters.
> Add smart type casting to CLI loader engine parameter options

- dragonfly/engines/backend_kaldi/engine.py
This is for merging after PR #302.
@Timoses Can you test this and see if it solves the crashing/errors in #286 ? You can use the KaldiAG dev wheel version.
> Fix Kaldi grammar loading/unloading while in phrase

- .travis.yml
https://devguide.python.org/#status-of-python-branches
> Travis CI: Test on current versions of Python

- dragonfly/engines/backend_natlink/engine.py
Fixes #338.
This was caused by a silly typo and a lack of testing.
> Fix AttributeError bug in natlink engine.py file

- dragonfly/actions/sendinput.py
This changes the `KeyboardInput` struct in `sendinput.py` to use the `MAPVK_VK_TO_VSC_EX` map type when translating virtual key codes on modern versions of Windows.  The `KEYEVENTF_EXTENDEDKEY` flag is added only if the scan code has a high byte of `0xe0` or `0xe1`, as per the documentation for `MapVirtualKeyExW()` ([available here](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-mapvirtualkeyexw)).
This removes the hardcoded list of extended keys.
This fixes (again) issue #287.
> Fix incorrect handling of extended scan codes on Windows

- documentation/related_resources.txt
Not tested but I think it's just the angle brackets. Thanks again for mentioning numen!
> Fix numen link

- README.rst
- documentation/index.txt
Changed the pip install
added the fork info higher and clarified the ambiguity about dragonfly and dragonfly2
> Update README.rst and docs to clarify confusing project names
