dragonfly/actions/sendinput.py

The keyboard support code has been updated to correctly handle
simulation of most extended keypresses. The ENTER key on the numpad
can't be simulated with the current design because the key shares a
virtual key code with the main ENTER key.

Updated the virtual keyboard extended key support

---

dragonfly/grammar/elements_compound.py

This works as expected if used as a literal, and is the only way to have the word 'comma' present in a command and recognized properly by Dragon, as far as I can tell.

Added comma to list of allowed symbols in a command.

---

dragonfly/log.py

This looks like something added for debugging purposes a long time ago that was accidentally committed.

Removed log cruft where the file handler is printed in each log statement

---

documentation/actions.txt
dragonfly/__init__.py
dragonfly/actions/__init__.py
dragonfly/actions/action_cmd.py
dragonfly/actions/actions.py

I've implemented the class I mentioned in https://github.com/synkarius/caster/pull/324. I've called it `RunCommand` instead of `TerminalCommand`. It is similar to dragonfly's `StartApp` action, but is designed for starting and interacting with command-line programs instead. It should handle command-line arguments properly and run on most platforms.
Thanks to @LexiconCode for the idea and some of the code using `subprocess`.
Shorthand example:
``` Python
from dragonfly import RunCommand
def func(proc):
for line in iter(proc.stdout.readline, b''):
print(line)
RunCommand('ping localhost', func).execute()
```
Subclass example:
``` Python
from dragonfly import RunCommand
class Ping(RunCommand):
command = "ping localhost"
def process_command(self, proc):
for line in iter(proc.stdout.readline, …
```

Add multi-platform RunCommand action

---

dragonfly/actions/action_text.py
dragonfly/actions/keyboard.py
dragonfly/actions/sendinput.py
dragonfly/engines/backend_natlink/engine.py

The purpose of this pull request is to get the code out there and visible in case I'm dropped on my head again and I'm unable to complete it. I still need to do more refactoring, including documentation improvements. I recommend against merging it at this time, though it should be fully functional.
This pull request contains a mostly complete implementation of Windows SendInput Unicode keyboard functionality and a `Text` action class designed to take advantage of it, as well as documentation improvements and minor refactoring. Many of the lines changed are minor formatting changes in order to get my linter to stop pestering me.
Changes made to the SendInput code follow the process [described in the relevant Windows documentation](https://docs.microsoft.com/en-us/windows/desktop/api/winuser …

Windows Unicode keyboard support.

---

documentation/test_grammar_elements_basic_doctest.txt
dragonfly/engines/backend_natlink/compiler.py
dragonfly/grammar/elements_basic.py

So after a few discussions on the Gitter channel with @lunixbochs regarding dragonfly's Repetition elements, I have done the following:
- Added an 'optimize' argument to the Repetition element.
- Modified the natlink compiler to compile Repetition elements using Dragon's repeat tag if 'optimize' is set to true.
- Changed the relevant doctest to test with 'optimize' set to both true and false.
- Updated documentation.
The 'optimize' argument is set to true by default. Dragon will not know about the min/max limits, but this should **decrease grammar complexity**! You can get the old behaviour by using `optimize=False`.
I've done a bit of testing with a grammar that would normally produce complexity errors and it didn't with this patch.
@LexiconCode IIRC Caster defines a max repetition limit …

Add optimization for Repetition elements

---

AUTHORS.txt
CHANGELOG.rst
documentation/actions.txt
dragonfly/__init__.py
dragonfly/actions/__init__.py
dragonfly/actions/action_context.py
dragonfly/actions/actions.py

Re: https://github.com/dictation-toolbox/Caster/issues/426
ContextAction is a utility class from Aenea that executes different actions depending on which context is currently active. This version of the class works without Aenea's functionality.
I've included some documentation, error handling for executing actions/matching contexts, as well as a usage example.
@calmofthestorm Just wondering if you are okay with this being merged. I have left the original license & copyright notice at the top of the file. I find this class invaluable and I think that some dragonfly and caster users might find it useful.

Add ContextAction class from Aenea

---

documentation/language.txt
dragonfly/__init__.py
dragonfly/language/__init__.py
dragonfly/language/base/integer.py
dragonfly/language/en/__init__.py
dragonfly/language/en/line_number.py
dragonfly/language/en/number.py
dragonfly/language/en/short_number.py
dragonfly/test/test_language_en_number.py

The motivation for this change was the following text editor function:
```
"<action> [line] <n> [to <nn>]"  : Function(action_lines),
```
```
Choice("action", {
"select": "",
"copy": "c-c",
"cut": "c-x",
"delete": "backspace",
"replace": "c-v",
}),
```
```
def action_lines(action, n, nn):
if nn:
num_lines = int(nn)-int(n)+1 if nn>n else int(n)-int(nn)+1
top_line = min(int(nn), int(n))
else:
num_lines = 1
top_line = int(n)
command = Key("c-g") + Text(str(top_line)) + Key("enter, s-down:" + str(num_lines) + ", " + action)
command.execute()
```
Which allows commands like "copy five to fifteen", etc. Quite useful.
The problem comes in large files where you are having to say commands like "replace line five hundred fifteen to five hundred twenty three", which is kind of verbose and unnatural. …

WIP - Add more flexible Integer class

---

dragonfly/windows/monitor.py

The [EnumDisplayMonitors](https://docs.microsoft.com/en-us/windows/desktop/api/winuser/nf-winuser-enumdisplaymonitors) function returns a [RECT structure](https://docs.microsoft.com/en-us/previous-versions//dd162897(v=vs.85)). The fields in this struct refer to the x,y coordinates of the top left and bottom right corners of a monitor, not the origin and dx,dy as the original code assumed.
This change uses the correct calculations for the Monitor object to behave correctly.

Use the correct dx and dy returned from `EnumDisplayMonitors`

---

dragonfly/engines/backend_natlink/dictation.py
dragonfly/engines/backend_sapi5/dictation.py
dragonfly/engines/backend_text/dictation.py
dragonfly/engines/base/dictation.py

In Python 3, `.encode("windows-1252")` returns a byte literal, which ends up causing errors when decoding grammars. This is perhaps not the most complete fix, but it's how we're handling it in other parts of the code. E.g. `backend_natlink/dictation.py`

Don't encode to windows-1252 in Python 3.

---

dragonfly/examples/dfly-loader-wsr.py

WSR in particular has a lag where the context of the foreground windows is not loaded until after the first utterance in the new window. This adds the hook and an example of how to use it from the WSR loader.
Fixes #68 
This is certainly not the most elegant way to fix this bug, so someone should feel free to take the bones of this and make something more beautiful.

Fix WSR engine context bug with a hook for foreground window changes

---

dragonfly/grammar/context.py

At the moment if you want to create a context which will trigger on multiple different windows you have to either do:
```
AppContext("context one") | AppContext("context two")
```
or
```
LogicOrContext(AppContext("context one"), AppContext("context two"))
```
Both of these are kind of verbose, especially with longer lists (e.g. lists of terminal emulators), and it seems as though a lot of people have their own individual workarounds. This PR modifies AppContext to allow lists of strings to be passed to title and executable as well as individual strings. E.g.
```
AppContext(["context one", "context two"])
```
~~The old class also had a slightly strange behaviour whereby if an executable and a title were passed, if the executable didn't match it would immediately break without checking the …

Modify AppContext to allow lists of contexts

---

dragonfly/__init__.py
dragonfly/grammar/context.py

Context class that evaluates a given function, whose return value is interpreted as a *bool*, determining whether the context is active.
The foreground application details are optionally passed to the function as arguments named *executable*, *title*, and/or *handle*, if any/each matches a so-named keyword argument of the function. Default arguments may also be passed to the function, through this class's constructor.

Add FuncContext class that determines context activity by callable arg

---

dragonfly/engines/base/dictation.py
dragonfly/grammar/elements_basic.py
dragonfly/test/test_dictation.py

Apologies for the second PR on the same thing, but I pretty quickly realised that the functionality I added in the last is somewhat limited and it will bug me if I don't fix it.
I still like the idea of calling methods on Dictation objects to modify the output, but only having access to string methods limits what you can do, for example there is no way (that I can see) to get camel case text using only string methods.
Two additions solve this problem. Firstly since camel case comes up a lot, if the user calls `Dictation().camel()` it will formatTextThisWay in the same way that e.g. `title()` would capitalise it. Secondly, for arbitrary formattings that can't be done using string methods, you can call `Dictation().apply(f)` where f is a function taking a string and returning the formatted …

Further Dictation additions

---

dragonfly/rpc/methods.py
dragonfly/test/test_rpc.py

Closes #80.
This includes 3 new RPC methods:
* `register_history(length=10, record_failures=False)` - registers an internal `RecognitionHistory` observer. Can optionally record recognition failures.
* `get_recognition_history()` - get a list of recognition history
* `unregister_history()` - unregister the observer.
@LexiconCode When you have the time, let me know if this is what you had in mind.

Add RPC methods for speech state & recognition history

---

README.rst
documentation/installation.txt
dragonfly/actions/_test_x11_text_key.py
dragonfly/actions/action_key.py
dragonfly/actions/action_text.py
dragonfly/actions/keyboard/__init__.py
dragonfly/actions/keyboard/_x11_base.py
dragonfly/actions/keyboard/_x11_libxdo.py
dragonfly/actions/keyboard/_x11_xdotool.py
setup.py

Xdotool should be replacing the current pynput implementation used on Linux. A libxdo implementation has also been added, which is faster than xdotool, but is disabled because it doesn't work properly with Python 3.x. Both of these have been adapted from Aenea's implementations.
This should fix #79 from my testing. Keys are not marked as synthetic any more and keyboard shortcuts seem to be working correctly.
I would like to allow specifying other key symbols and characters through `Key` and `Text`. E.g. `Key("XF86Mail")` and `Text("€", is_text=True)`. Example 2 is already possible on Windows.
I am hoping to use more of Aenea's xdotool implementation for X11 `Mouse` and `Window` classes.
@shervinemami @dwks @GoNZooo @calmofthestorm You all may be interested in this :-)

Add xdotool & libxdo keyboard implementations

---

dragonfly/actions/action_base.py
dragonfly/test/suites.py
dragonfly/test/test_actions.py

As mentioned on Gitter, I think that the most natural and common use case for the `Repeat` class is to repeat actions an arbitrary number of times, rather than a prespecified number of times. For example:
```
"close tab [<n>]"         : Key("c-w/3")*Repeat(extra="n"),
```
This usage comes up over a hundred times in Caster, every time requiring the `extra` argument to be explicitly specified because it comes after the `count` argument.
Swapping the order of the arguments is a fairly minor change but I think it would be worthwhile. One less piece of syntax for users to remember for fairly basic operations is always a good thing.
In order to maintain backwards compatibility for e.g. `Repeat(3)` I have introduced a type check which should make it do what the user intended even if the order is …

Swap Repeat arguments

---

documentation/window_classes.txt
documentation/windows.txt
dragonfly/actions/__init__.py
dragonfly/actions/action_focuswindow.py
dragonfly/actions/action_waitwindow.py
dragonfly/actions/actions.py
dragonfly/actions/keyboard/_x11_xdotool.py
dragonfly/os_dependent_mock.py
dragonfly/test/suites.py
dragonfly/windows/__init__.py
dragonfly/windows/base_window.py
dragonfly/windows/fake_window.py
dragonfly/windows/win32_window.py
dragonfly/windows/window.py
dragonfly/windows/x11_window.py
setup.py

Related issues: #8 #35 #77 
This PR does quite a few things. This is a summary of the changes:
- Add `X11Window` class using xdotool and xprop.
Big thanks to @calmofthestorm for Aenea's xdotool/xprop code!
This class can do pretty much everything the Windows-only class can do:
- Get various attributes available from xprop / xdotool (title, class, class name, executable, pid, id/handle). **This allows `AppContext` to work on X11**! 🎉🎉
- Common operations like minimize, maximize, restore, set foreground, set focus.
- Get/set geometry with `get_position()`, `set_position()` and `move()`. This includes the fun window movement functionality in `window_movers.py`, which animates windows as they move.
- Get window state, e.g. if a window is focused, minimized, maximized, in fullscreen mode, etc. …

Add additional Window classes and change the old one

---

documentation/kaldi_engine.txt

Changed kaldi-active-grammar url from v0.4.0 to releases (latest)

Update kaldi-active-grammar URL

---

dragonfly/windows/win32_window.py

Re: #86.
This is done by pressing the control key before calling `SetForegroundWindow()`. Doing this allows the process to call the function because it received the last input event (see [`SetForegroundWindow()` documentation](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setforegroundwindow#remarks)).
This worked for me on Windows 7 and Windows 10. I don't really use metro applications, but it seems to work with the new calculator app.
As I mentioned in the issue for this bug, the function still won't work if the current window is running in elevated mode, i.e. as the administrator.
@jcaw Please let me know if this works for you.

Fix Win32Window.set_foreground() failures

---

dragonfly/engines/backend_natlink/dictation_format.py

The dragonfly file dictation_format.py provides autoformatting behavior for built-in Dragon vocabulary words with `property` values which indicate whether there should be for example a space before and/or after the word or whether the next word should be capitalized and things like that. However this does not currently work with custom words in the Dragon vocabulary. Even when you set those properties for your custom words in the Dragon vocabulary (using the word properties GUI or the XML file for your vocabulary), the value of `property` in dictation_format.py is just blank.
This pull request allows people to set formatting flags for their custom words. Two example customer words are provided (commented out): "len" which is supposed to be a short name for "(" and "ren" which is supposed …

Custom words formatting

---

dragonfly/__init__.py
dragonfly/log.py

This should fix the "No handlers for logger X" error message that occurs if using dragonfly without a module loader or the `setup_log()` function.
I've also added sane default log levels for dragonfly's RPC server dependencies. This only applies if `setup_log()` is called.
@MatthijsBurgh let me know if #115 is not fixed by this :-)

Fix some logging issues

---

dragonfly/windows/base_window.py
dragonfly/windows/fake_window.py
dragonfly/windows/win32_window.py
dragonfly/windows/x11_window.py

As far as I can tell the window classes do not contain methods for closing windows. `Win32Window` has a `_destroy` method which gives me a permission error, and `win32gui` has a `CloseWindow` function which (obviously) *minimises* the window.
[This stack overflow post](https://stackoverflow.com/questions/27586411/how-do-i-close-window-with-handle-using-win32gui-in-python/27658320) post gives a functional windows implementation.
While `Key("a-f4")` obviously works fine for closing the active window, an example usage for this would be something like:
```
def close_program(title_match):
program_windows = Window.get_matching_windows(title=title_match)
for window in program_windows:
window.close()
```

Add close method to Window classes

---

dragonfly/windows/base_window.py

Ran into a bug when testing the Kaldi backend with Python 2. If the window title contains Unicode characters then `_win32gui_func("GetWindowText")` returns bytes, which get passed to the context matcher and cause an error.
This is not a problem with Natlink, which contains this function (`engine.py`):
```
def map_word(word, encoding=getpreferredencoding(do_setlocale=False)):
if isinstance(word, text_type):
return word
elif isinstance(word, binary_type):
return word.decode(encoding)
return word
```
which it uses to sanitise the window info before it is processed:
```
def begin_callback(self, module_info):
executable, title, handle = tuple(map_word(word)
for word in module_info)
self.grammar.process_begin(executable, title, handle)
```
The same is not done for other engines however, hence …

Fix Unicode window titles with non-Natlink backends

---

documentation/elements.txt
documentation/test_grammar_elements_basic_doctest.txt
dragonfly/__init__.py
dragonfly/grammar/elements.py
dragonfly/grammar/elements_basic.py
dragonfly/grammar/elements_compound.py
dragonfly/test/test_dictation.py
dragonfly/test/test_engine_text_dictation.py

Following the suggestion from @wolfmanstout in #96 I have implemented a new element which allows the output of any other element to be modified according to some function.
I was originally planning to do this using a method on `ElementBase` but this gets complicated quickly when you have a tree of elements and you only want to apply the function to one of them, so I think this is the simplest and clearest way.
@Danesprite it would be good to get your input on what to do about the issues with methods like `deepcopy` on `Dictation` objects. The modifier class provides similar functionality to calling methods on dictation objects, but is perhaps more verbose. We could either decide that the complexities of overriding `__getattr__` are not worth the gains and I can revert the modifications to …

Implement Modifier element and fix Dictation deep copy issue

---

dragonfly/actions/action_base.py
dragonfly/grammar/elements_basic.py
dragonfly/grammar/recobs.py
dragonfly/windows/clipboard.py
dragonfly/windows/point.py

Allow Python 2 longs for max recognitions and in other places

---

documentation/kaldi_engine.txt

The example errors if the `xdotool` is not installed when you try to run this.
The error I got on ubuntu is as follows:
```
window (ERROR): Failed to execute command 'xdotool getactivewindow': [Errno 2] No such file or directory
Traceback (most recent call last):
File "./dragonfly/examples/kaldi_demo.py", line 60, in <module>
engine.do_recognition()
File "/home/jasoons/.local/share/virtualenvs/dragonfly-zX3FzRWY/local/lib/python2.7/site-packages/dragonfly/engines/backend_kaldi/engine.py", line 233, in do_recognition
kaldi_rules_activity = self._compute_kaldi_rules_activity()
File "/home/jasoons/.local/share/virtualenvs/dragonfly-zX3FzRWY/local/lib/python2.7/site-packages/dragonfly/engines/backend_kaldi/engine.py", line 286, in _compute_kaldi_rules_activity
fg_window = …
```

Add note about requiring the `xdotool` to be installed in kaldi example.

---

dragonfly/engines/backend_kaldi/engine.py
dragonfly/engines/backend_natlink/engine.py
dragonfly/engines/backend_sapi5/engine.py
dragonfly/engines/backend_sphinx/engine.py
dragonfly/engines/backend_text/engine.py
dragonfly/grammar/grammar_base.py

Before being compiled grammars need to loop through the rules the user has added and add their dependencies. Previously this was done manually in the engines but makes much more sense as a method on the grammar class.
Tagging @daanzu.
Edit: Also, in every engine's `_load_grammar` method there is the line:
```
grammar.engine = self
```
this seems redundant since in order to get to that stage the grammar had to have called:
```
self._engine.load_grammar(self)
```
so it must have the engine set already. Am I missing something?

Remove duplicate dependency adding code

---

dragonfly/grammar/context.py
dragonfly/windows/win32_window.py

This allows using `AppContext` to match window attributes other than the title and executable. For example, matching `cls` or `cls_name` on X11, similar to what Aenea's `ProxyAppContext` function allows. This will work with any existing window property or attribute.
It works by getting a window using the `handle` parameter.
@mrob95 I've also made this work with your list additions added by #82. This is especially useful on X11/Linux where the `cls` and/or `cls_name` properties are more meaningful than the executable.
Some examples:
```Python
AppContext(executable="firefox", is_maximized=True)
AppContext(role="browser", is_fullscreen=True)
AppContext(cls=["jetbrains-studio", "jetbrains-pycharm-ce"])
```
I've implemented the missing `Win32Window.is_maximized` property in this PR too. Just …

Add keywords argument handling to AppContext class

---

dragonfly/grammar/state.py

This is surprisingly dominant in CPU profiling, based on yappi. Seems like a pretty simple and safe improvement.

Add check to avoid unnecessarily preparing expensive debug log messages

---

documentation/monitor_classes.txt
documentation/windows.txt
dragonfly/actions/__init__.py
dragonfly/actions/action_mouse.py
dragonfly/actions/actions.py
dragonfly/actions/mouse/__init__.py
dragonfly/actions/mouse/_base.py
dragonfly/actions/mouse/_pynput.py
dragonfly/actions/mouse/_win32.py
dragonfly/os_dependent_mock.py
dragonfly/windows/__init__.py
dragonfly/windows/base_monitor.py
dragonfly/windows/base_window.py
dragonfly/windows/darwin_monitor.py
dragonfly/windows/monitor.py
dragonfly/windows/win32_monitor.py
dragonfly/windows/win32_window.py
dragonfly/windows/x11_monitor.py
setup.py

Re: #8.
This PR implements mouse support for Linux and Mac OS via [`pynput`](https://github.com/moses-palmer/pynput).
I've moved all internal mouse event classes, flags and functions into modules under a new `dragonfly/actions/mouse` sub-package, similar to the `keyboard` sub-package. Windows functionality should be completely unaffected by these changes. From my testing, it seems to work just as it did before.
Mouse button and scroll events all work in X11. `pynput` doesn't seem to support scrolling or the `"four"`/`"five"` buttons on Mac OS. The `"left"`, `"right"` and `"middle"` buttons seem to work properly though.
I won't merge this just yet because I want to get the `Monitor` class working on Linux so that relative mouse movements work correctly.
Mouse movements **do not yet work …

Implement mouse and monitor functionality for X11 & Mac OS

---

dragonfly/engines/backend_text/__init__.py
dragonfly/engines/backend_text/engine.py

I'm finding the text engine extremely useful for debugging. This PR extends the functionality of `mimic` slightly by allowing e.g.
```
engine.mimic(["new", "tab"], executable="firefox", title="google")
```
So that correct context switching behavior can be checked.

Allow the passing of window attributes to text engine mimic

---

dragonfly/engines/backend_text/engine.py

At the moment, any `process_begin` call or any processed command (e.g. caster's "enable...") which loads a new grammar will cause a runtime error, because the _grammar_wrappers dict is mutated as it is being iterated over. This is fixed by using a copy of the dict.
New problem: if a new grammar is added during `process_begin` then this will not be available for processing immediately, because we are still iterating over the old grammar dict copy. This is fixed by splitting the `process_begin` step from the `process_words` step, as would happen in an actual engine.

Fix text engine bugs

---

dragonfly/engines/backend_natlink/engine.py
dragonfly/engines/backend_sapi5/engine.py
dragonfly/engines/backend_sphinx/grammar_wrapper.py
dragonfly/engines/backend_text/engine.py
dragonfly/grammar/rule_compound.py

I've come across two confusing issues related to exported and non-exported rules today:
1. `CompoundRule` sometimes refuses to be used as a non-exported rule. If `exported=False` is passed to the constructor without overriding the class-level `exported` definition, then the rule will actually be an exported rule.
I've fixed this by re-using the logic from `MappingRule` and removing the `exported = True` line which was overriding the base class's `exported` property.
2. Non-exported rules can sometimes be mimicked.
This is obviously undesirable, as `mimic()` should work like normal speech does, with only top-level rules being recognisable.
The Natlink and SAPI5 engines seem to disallow this internally anyway. I noticed the problem when testing with the Sphinx and text engines and have …

Fix problems relating to exported and non-exported rules

---

documentation/object_model.txt
documentation/recobs.txt
documentation/test_recobs_doctest.txt
dragonfly/__init__.py
dragonfly/grammar/recobs.py
dragonfly/grammar/recobs_callbacks.py

This adds new functions for recognition state change callbacks and should close #124. The following is a simple usage example:
```Python
from dragonfly import *
def on_begin():
print("on_begin()")
def on_recognition(words):
print("on_recognition(): %s" % (words,))
def on_failure():
print("on_failure()")
register_beginning_callback(on_begin)
register_recognition_callback(on_recognition)
register_failure_callback(on_failure)
```
I decided against adding the `unregister` functions mentioned in #124 because each register function returns a recognition observer that can be unregistered with `observer.unregister()`.
I've also added doctests for these new functions and a separate documentation page for recognition observers under the [object …

Make improvements to recognition observers and documentation

---

dragonfly/grammar/elements_basic.py
dragonfly/grammar/grammar_base.py
dragonfly/grammar/rule_base.py
dragonfly/parser.py

Profiling caster's start-up produces this:
```
34793638 function calls (32510155 primitive calls) in 24.034 seconds
Ordered by: internal time
List reduced from 4160 to 1248 due to restriction <0.3>
ncalls  tottime  percall  cumtime  percall filename:lineno(function)
106    2.953    0.028    2.953    0.028 {method 'acquire' of 'thread.lock' objects}
646083/163188    1.797    0.000   14.751    0.000 parser.py:409(parse)
1296417    1.586    0.000    3.657    0.000 parser.py:211(decode_attempt)
2997654    1.414    0.000    3.485    0.000 parser.py:267(_log_step)
2997878    1.219    0.000    2.071    0.000 __init__.py:1367(isEnabledFor)
492119/29710    0.999    0.000    1.677    0.000 parser.py:187(_build_parse_node)
806866    0.929    0.000    1.414    0.000 …
```

Various optimisations

---

dragonfly/engines/backend_kaldi/engine.py

After interrupting the engine, last dictation was not being saved. I do not understand using the deque as opposed to saving directly, so this just saves remaining items on exit. Great feature by the way

Retain even the last dictation in Kaldi backend

---

dragonfly/grammar/rule_base.py

The old default of exported=False differing from CompoundRule and
MappingRule is endlessly surprising for newbies (and experts).
Somewhat fixes #142.

Make exported=True default for base Rule

---

dragonfly/engines/backend_kaldi/engine.py

More or less the same fix as in #149, making sure that phrase begin callbacks can safely make changes to grammars.

More robust activity checking in kaldi engine

---

dragonfly/actions/action_startapp.py

This allows passing a single list or tuple argument to the `StartApp` / `BringApp` constructor, instead of using variable arguments.
This is more in-line with the main argument for `Popen()`.
@kendonB This should fix the problem you were having with `BringApp`.

Allow using StartApp and BringApp actions with lists/tuples

---

dragonfly/engines/backend_kaldi/testing.py

@daanzu Just letting you know I'm changing this because the behaviour of `time.clock()` varies between platforms. It counts wall clock time on Windows and CPU time on Linux. The function will also be removed in Python 3.8.
It's not a big problem, but you might want to fix it in [kaldi_active_grammar/utils.py](https://github.com/daanzu/kaldi-active-grammar/blob/master/kaldi_active_grammar/utils.py#L31) too.
Only noticed these things because I got some warnings when running the Kaldi tests in Python 3.7 ;-)

Change time.clock() to time.time() in Kaldi debug_timer() func

---

dragonfly/engines/backend_kaldi/audio.py

This stops `save_all()` raising an error if `deque` is `None`. Usually happens when I interrupt the Kaldi module loader with Ctrl+C.
@daanzu Just FYI :-)

Fix minor Kaldi bug in AudioStore.save_all() method

---

dragonfly/grammar/elements.py
dragonfly/grammar/elements_compound.py
dragonfly/language/base/integer_internal.py
dragonfly/parsing/__init__.py
dragonfly/parsing/grammar.lark
dragonfly/parsing/parse.py
dragonfly/test/suites.py
dragonfly/test/test_lark_parser.py
setup.py

This has been bugging me all week so I finally took another look at it. Turns out I was using the slow, forgiving lark parser (Earley) rather than the fast, extremely uncooperative parser (LALR).
Headlines:
* Tests down from 6s to 3s
* Breathe start-up down from ~3s to <1s
* Caster start-up down from ~20s to <10s
* Major simplification
This is still a work in progress, although I *think* I have caught at least most of the potential edge cases. The only thing remaining that it doesn't like in caster is `"((meth|method)|(meth|method)s)"` in `ide_shared.py`. I don't think this should actually be valid syntax, but am willing to be persuaded.
As I said, LALR is quite unforgiving and the error messages are not brilliant so modify this at your peril :-). I tried a lot of things which I thought …

New parser!

---

documentation/actions.txt
dragonfly/actions/__init__.py
dragonfly/actions/action_playsound.py
dragonfly/actions/actions.py
dragonfly/os_dependent_mock.py

- Add documentation and examples.
Re: #77.
- Implement the action for other platforms using PyAudio.
I've tested that the action works perfectly on Windows, Mac OS and Linux-based systems.
`pyaudio` is effectively a soft-dependency on platforms other than Windows. `PlaySound` will raise an error when executed if `pyaudio` isn't installed.
- Make the action play sound synchronously instead because it avoids having to handle file queues and errors from other threads.
Although this PR removes the last internal use of `dragonfly/os_dependent_mock.py`, I'm leaving it in because Caster's tests make use of the file's `MockAction` class.

Make changes to the PlaySound action

---

MANIFEST.in
setup.py

I've included "grammar.lark" in Dragonfly's `MANIFEST.in` file, which closes #169.
@LexiconCode Thanks for the suggestion :+1:

Fix missing file error for "grammar.lark"

---

dragonfly/engines/backend_kaldi/engine.py
dragonfly/engines/backend_natlink/engine.py
dragonfly/engines/backend_sapi5/engine.py
dragonfly/engines/backend_sphinx/engine.py
dragonfly/engines/backend_text/engine.py
dragonfly/engines/base/engine.py
dragonfly/examples/dfly-loader-natlink.py
dragonfly/examples/dfly-loader-wsr.py
dragonfly/examples/kaldi_module_loader.py
dragonfly/examples/kaldi_module_loader_plus.py
dragonfly/examples/sphinx_module_loader.py
dragonfly/examples/wsr_module_loader_plus.py

This is being done to unify the engine interface a bit. Aliases of renamed methods have been left in for backwards compatibility.
@daanzu @comodoro @jcaw This is the PR I mentioned on Gitter earlier.

Change engine recognition loop method names to 'do_recognition'

---

dragonfly/actions/action_base_keyboard.py
dragonfly/actions/action_key.py
dragonfly/actions/action_text.py
dragonfly/actions/keyboard/_base.py
dragonfly/actions/keyboard/_win32.py
dragonfly/actions/sendinput.py

Re: #81, #114.
This adds a Windows-specific `Typeable` class and changes the keyboard class to call `get_keycode_and_modifiers()` during the `Typeable` event methods instead, so that the current foreground window's keyboard layout is taken into consideration when typing keys. This applies to the `Key` and `Text` actions.
Unknown character errors aren't completely removed by this. One way to remove them altogether is to fallback on the Unicode keyboard interface if [`VkKeyScanEx()`](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-vkkeyscanexw) returns `-1`. As I mentioned in https://github.com/dictation-toolbox/dragonfly/issues/81#issuecomment-515762324, this means modifier keys won't work in some circumstances, e.g. executing `Key("c-c")` when the current layout …

Win32 keyboard improvements

---

dragonfly/windows/win32_window.py

This stops `get_matching_windows()` from returning windows with a class name of "#32770" or "DgnResultsBoxWindow". The second name is used in more recent Dragon versions.
This indirectly fixes the `FocusWindow` action.
Thanks for bringing this to my attention @lettersandnumbersgithub and @mrob95!

Fix Win32Window.get_matching_windows() for recent Dragon versions

---

dragonfly/actions/action_startapp.py
dragonfly/windows/base_window.py
dragonfly/windows/fake_window.py
dragonfly/windows/win32_window.py
dragonfly/windows/x11_window.py

Re: #158.
- Handle single list and tuple arguments correctly.
- Raise an intelligible TypeError for other non-string arguments.
- Add Window.pid property and backing _get_window_pid() method.
- Add optional 'title' constructor argument to BringApp action.
- Add optional 'focus_after_start' argument to StartApp action.
This also applies to BringApp if the application isn't running yet.

Change/fix bugs with StartApp & BringApp action classes

---

dragonfly/actions/action_key.py

Bug got introduced somewhere recently, `Key("")` currently raises an unpacking error.

Fix empty key action

---

dragonfly/actions/action_cmd.py

- Fix threading issue with the RunCommand action under natlink.
Natlink doesn't really allow other threads to work, so use an engine timer to workaround that. This only applies when the action is used asynchronously.
- Fix the RunCommand action's handling of subprocess output.
Properly decode output using the preferred system charset and stop printing extra new lines for each line in the output.
- Add optional 'hide_window' argument to RunCommand action.
This argument is useful if using RunCommand to start a GUI application on Windows. The argument is False by default to avoid showing cmd.exe windows unnecessarily.
CC @lettersandnumbersgithub

Fix problems with the RunCommand action

---

dragonfly/actions/action_startapp.py

Re: #173.
These arguments are passed through to the internal `FocusWindow` action used by the action.

Add new 'index' and 'filter_func' arguments to BringApp action

---

dragonfly/engines/backend_natlink/dictation_format.py

Closes #179.
This PR suppresses the unknown word property warning message when "numeral" is used with `Dictation` elements. The `"no_space_after"` word flag is used to be consistent with similar special Dragon words like "letter".
This doesn't change Dragonfly's DNS dictation formatters to emit "numeral" because this would deviate from how Dragon handles special words like this. See https://github.com/dictation-toolbox/dragonfly/pull/179#issuecomment-560193135 for a simple way to make Dragonfly type special words like "numeral", "cap", "letter", etc.

Add missing DNS parser entry for the special "numeral" word

---

dragonfly/parsing/grammar.lark
dragonfly/parsing/parse.py
dragonfly/test/test_lark_parser.py

Allows for adding attributes, either a specific value or just True. Must come at the end of a `Sequence`, and applies to that whole `Sequence` (or whatever more specific `Element`). The main impetus for this is easily specifying weights for Kaldi, but trying to making it flexible for future/other additions.
Examples:
* "alpha {weight=2}"
* "test <an_extra> [op] {test_special}"
* "foo | bar {test_special} | baz"
I am open to suggestions for the best implementation.

Add support for special specifiers to Compound specs

---

documentation/conf.py
documentation/window_classes.txt
dragonfly/windows/darwin_window.py
dragonfly/windows/window.py
setup.py

Re: #8, #35.
This is a work-in-progress `Window` class implementation for Mac OS using `py-applescript`. It is based on Aenea's Mac OS server implementation ([located here](https://github.com/dictation-toolbox/aenea/blob/master/server/osx/server_osx.py)).

Add Window class for Mac OS using AppleScript

---

dragonfly/actions/mouse/_win32.py

Closes #185.
This fixes a bug that occurs when the primary and secondary mouse buttons are inverted using the Windows control panel. Dragonfly's Mouse action would press the wrong buttons: left instead of right
and vice versa.
This bug has been fixed by restoring the normal left/right primary and secondary buttons and swapping back afterwards if necessary.

Fix a Windows bug where the wrong mouse buttons may be pressed

---

dragonfly/actions/action_paste.py
dragonfly/actions/action_text.py
dragonfly/actions/sendinput.py

I made a few minor adjustments just because they were relatively straightforward and I need some momentum. At some point, the platform check should probably be done in the configuration module I never got around to properly implementing.
>The platform check in `Paste` and `Text` is now done once upon class instantiation.
Additionally, `Text` no longer generates Windows Unicode keyboard events unless it's necessary.
In `KeyboardInput` from `actions/sendinput.py`, the lists `self.extended_keys` and `self.soft_keys` have been turned into sets to improve membership test times and the test against `self.extended_keys' now only happens for non-Unicode key events.

Minor speed optimizations.

---

dragonfly/engines/backend_natlink/engine.py
dragonfly/engines/backend_natlink/recobs.py

The `on_recognition()` callback is now called *before* rule processing, as it is for other engines.
CC @lettersandnumbersgithub

Fix on_recognition() observer callback for the natlink engine

---

dragonfly/test/suites.py
setup.py

It would be nice to have an CLI option to enable this, but I'm not sure how to add to it correctly/cleanly.

Support running the test suites with different pytest options

---

dragonfly/actions/action_focuswindow.py
dragonfly/actions/action_startapp.py
dragonfly/windows/base_window.py
dragonfly/windows/darwin_window.py
dragonfly/windows/fake_window.py
dragonfly/windows/win32_window.py

This PR implements `set_focus()` methods for each `Window` class and allows using it in the `BringApp` and `FocusWindow` actions via an optional `focus_only` argument (`False` by default). The `X11Window` class has the `set_focus()` method since it was introduced (#102).
`set_focus()` and `focus_only` only currently do anything different on X11 (Linux). Windows and macOS don't seem to support focusing windows without raising them, so `set_focus()` is just an alias for `set_foreground()` on those platforms.

Support focusing windows without raising them on X11

---

documentation/cli.txt
dragonfly/__main__.py
dragonfly/loader.py

Re: #98.
These commands are alternatives to Dragonfly's module loader scripts. Available options are similar to the "test" command options, with some new additions. The commands are working nicely with each engine backend. Recognition state messages are on by default, but can be disabled using the `--no-recobs-messages` option.
I'm not sure if the module loader scripts should be changed to use the `__main__.py` CLI functions directly. It just doesn't seem like it would be worth the effort. Most of the scripts aren't very long anyway.
Engine options can be specified via the `-o` / `--engine-options` command-line options. Here is an example:
```Shell
python3 -m dragonfly load-directory --engine kaldi --engine-options model_dir=kaldi_model_zamia .
```
The Kaldi engine needs to be modified to …

New load & load-directory CLI sub-commands + CLI code cleanup

---

documentation/cli.txt
dragonfly/__main__.py

This is required for shells like cmd.exe that can't really handle glob patterns like '_*.py'. The application has to do the work.
These changes should make the following example commands work properly on Windows using cmd.exe or MS PowerShell:
```Shell
python -m dragonfly test dragonfly/examples/_*.py
python -m dragonfly load dragonfly/examples/_*.py
```
These commands already worked properly on Unix/POSIX shells like Bash.
Thanks @LexiconCode for bringing this to my attention :-)

Change Dragonfly's CLI to expand glob patterns where necessary

---

documentation/conf.py
dragonfly/engines/__init__.py
dragonfly/engines/backend_kaldi/__init__.py
dragonfly/engines/backend_kaldi/engine.py
dragonfly/engines/backend_natlink/__init__.py
dragonfly/engines/backend_natlink/engine.py
dragonfly/engines/backend_sapi5/__init__.py
dragonfly/engines/backend_sphinx/__init__.py
dragonfly/engines/backend_sphinx/engine.py

The purpose of this pull request is to enhance error messages related to dependencies for speech recognition engines.  These checks will help inform users during call to get engine and the CLI.
The enhancements include:
Natlink
- Checking OS (only Windows is supported)
- Rewording message checking for natlink clarifying that it needs to be installed.
- Checking python environment to ensure its 32-bit
WSR
- Checking OS (only Windows is supported)
kaldi
- Checking python environment to ensure its 64-bit
All Backends
- Check if the requested engine name is a supported engine.
Example output
```
PS D:\Backup\Library\Documents\Caster> cmd /c python -m dragonfly load --engine foo _caster.py
ERROR:command:Requested engine 'foo' is not a valid engine name.
```

Enhance engine dependency checks and log messages

---

documentation/test_action_base_doctest.txt
dragonfly/actions/action_function.py

This avoids a deprecation warning. The old `getargspec()` function is still used in Python 2.7, as it doesn't have `getfullargspec()`.
I've also added the `Function` action doctests in `action_function.py` into `documentation/test_action_base_doctest.txt` so they are run with Dragonfly's test suites.

Fix Function action deprecation warning and add doctests

---

dragonfly/actions/action_base.py

This fixes inconsistent behavior before. Allowing the user to specify
specific behavior could still be implemented by checking the return
value of Action.execute().

Catch all exceptions while executing Actions

---

dragonfly/actions/action_startapp.py
dragonfly/windows/darwin_window.py

This PR fixes the problem of identifying correctly windows of child process that share the same name but have unique IDs (e.g. all child processes of Caster have the same name Python).

Make some improvements to Dragonfly's macOS support

---

documentation/test_action_base_doctest.txt
dragonfly/actions/action_base.py

This action class has the previous behaviour of `ActionSeries` where the series continues executing after an action fails. I've also updated the action doctests with cases on series execution failure.
```Python
from dragonfly import Key, Function
(Key("a") + Function(lambda: 1/0) + Key("b")).execute()
(Key("a") | Function(lambda: 1/0) | Key("b")).execute()
```
@daanzu This is what you had in mind, right?

Add UnsafeActionSeries class to be used via the | and |= operators

---

documentation/test_grammar_elements_basic_doctest.txt
dragonfly/__init__.py
dragonfly/engines/backend_kaldi/compiler.py
dragonfly/engines/backend_natlink/engine.py
dragonfly/engines/backend_sapi5/compiler.py
dragonfly/engines/backend_sapi5/engine.py
dragonfly/engines/backend_sphinx/engine.py
dragonfly/engines/backend_text/engine.py
dragonfly/grammar/elements_basic.py

This makes the Kaldi backend's compiler handle the Empty element in the
same way that the natlink backend handles it - by doing nothing with it.
Fixes #210.

Make Kaldi and SAPI5 compilers handle Empty and Impossible elements

---

dragonfly/windows/win32_window.py

This changes the `Win32Window.set_foreground()` method to only press and release control if the key isn't currently held down.
Control is pressed in that method as a workaround to get Windows to reliably set the foreground window (see PR #106). This will break that workaround in some cases. This is largely unavoidable. If it becomes a problem, then the method could be changed to press a key that isn't used as frequently.

Fix Win32 modifier bug where control could be released if held down

---

dragonfly/windows/darwin_window.py

If these methods are called with application process id that no longer
exist, applescript will throw an exception.  This fix catches the
exception and returns empty module name and non-existent process id.

Make darwin get_window_module/pid error safe

---

dragonfly/actions/action_base.py
dragonfly/actions/action_function.py
dragonfly/actions/action_key.py
dragonfly/actions/action_mouse.py
dragonfly/actions/action_text.py
dragonfly/test/test_actions.py

I would like to add these method for rules visualization purposes.  They provide mnemonic representation of actions that can be used to visualize the actions dragonfly rules invoke.

Add __str__ method to essential action classes for visualization

---

dragonfly/engines/backend_natlink/__init__.py

Fixes #222.
This adds Natlink's default 'core' directory to 'sys.path' in the event it fails to be imported during `is_engine_available()`. The path is added if it is a valid path and contains the  'natlink.pyd' file. This should allow natlink's modules to be imported.
Thanks @LexiconCode for most of this code.

Verify that natlink is on the Python path in is_engine_available()

---

dragonfly/__main__.py
dragonfly/actions/action_base.py
dragonfly/examples/dfly-loader-natlink.py
dragonfly/examples/dfly-loader-wsr.py
dragonfly/examples/kaldi_module_loader_plus.py
dragonfly/examples/sphinx_module_loader.py
dragonfly/examples/wsr_module_loader_plus.py

Fixes #203.
This changes Dragonfly's command-line interface and module loader scripts to suppress encoding errors in builtin `on_recognition()` callbacks when the character set of the output stream doesn't define special characters. This problem is specific to Python 2.7.
This also fixes a `UnicodeDecodeError` with the `BoundAction` class that could occur if non-ASCII characters were present in the action or data representation.
Even though Python 2.7 is end-of-life, I'm still fixing bugs specific to it because I am fairly certain that the majority of Dragonfly users still use Dragon and Natlink. Dragonfly's Natlink engine backend doesn't support Python 3.x yet, so I will not be dropping support for Python 2.7 until it does. And, to give people time to transition to Python 3, it will be …

Fix some Python 2.7 encoding bugs

---

dragonfly/grammar/elements_basic.py

If the `format` constructor argument is `False`, then the element will return a list of the recognized words instead of a `DictationContainer` object. The argument's default value is still `True`.
This argument previously had no effect.

Make the Dictation element's 'format' argument do something useful

---

dragonfly/engines/backend_natlink/__init__.py

CC @LexiconCode.
The message is now less confusing and more consistent with other messages logged in the Natlink backend's `is_engine_available()` function.

Reword Natlink warning message shown when Dragon isn't running

---

dragonfly/actions/action_mouse.py
dragonfly/windows/base_monitor.py
dragonfly/windows/darwin_monitor.py
dragonfly/windows/win32_monitor.py
dragonfly/windows/x11_monitor.py

This PR changes the Win32 monitors list to always have the primary monitor first.
@MarkRx This fixes #228 for me. Please let me know if it fixes it for you.
I have also added a `Win32Monitor` `name` property that returns the device name, e.g. `"\\.\DISPLAY1"`. Device names reflect the monitor IDs shown in the control panel.

Monitor changes

---

dragonfly/grammar/context.py
dragonfly/windows/x11_window.py

This fixes handling of a strange scenario on Linux X11 that I haven't bothered putting time into fully understanding, but I have found a solution that works for me, and shouldn't hurt anyone by adding this guard.
Details:
In my Linux machine (using the KDE Neon distro based on Ubuntu 18.04, and using Dragonfly 0.21 with KaldiAG v1.3.0 backend), if I run the command:
`kdialog --msgbox "Hello"`
then a popup dialog is shown, and I can use Dragonfly to press Enter, as expected.
But if a dialog is created by the "root" super user:
`sudo kdialog --msgbox "Hello"`
if I say anything while this dialog is active, then Dragonfly crashes because the "executable" variable is empty:
```
Speech start detected.
Traceback (most recent call last):
File "kaldi_module_loader_plus.py", line 425, in <module> …
```

Support edge case of X11 backend when executable isn't valid

---

documentation/faq.txt
dragonfly/__init__.py
dragonfly/engines/__init__.py

CC @daanzu
This function returns the current SR engine. If an SR engine has not been initialized yet, then `None` will be returned instead. This is in contrast to the `get_engine()` function which will initialize an SR engine if one is not initialized yet.
One good use case for this is checking the current engine name.

Add get_current_engine() function that doesn't initialize an engine

---

dragonfly/engines/backend_natlink/engine.py
dragonfly/engines/backend_sapi5/engine.py
dragonfly/engines/base/engine.py

Rather than always returning "en", the `engine.language` property now returns a language tag matching the language selected in the Windows Speech Recognition options window.
The internal language tag matching code in `NatlinkEngine` has been moved to the `EngineBase` class so both engine classes can use it.

Change SAPI5 engine backend to use the recognizer language

---

dragonfly/engines/backend_kaldi/compiler.py
dragonfly/engines/backend_kaldi/engine.py

I am not sure how this will interact with `setup_log()`, as I don't have much experience with it.

Add Kaldi temporary mitigation for keyboard action processing bug (#182)

---

dragonfly/actions/action_base.py
dragonfly/actions/action_function.py
dragonfly/actions/action_key.py
dragonfly/loader.py
dragonfly/test/test_actions.py

- Command module files are now always opened in binary mode 'rb'.
This stops Python 3.x from using potentially incorrect character
encodings to decode source code files.
- Command module files are now correctly closed after being opened
and read from.
- Fix `__str__` visualization methods that break Unicode support.
Re: #219.
This also adds some extra test cases in test_actions.py.
- Add missing `__str__` visualization method for UnsafeActionSeries.
This uses the '|' separator instead of '+' and includes a test in
test_actions.py.
- Add missing catch for IOErrors in the `Function.__str__()` method
An IOError is raised if the inspect module couldn't get the
function's source code.

Fix various encoding bugs and related issues

---

dragonfly/log.py
dragonfly/test/test_log.py

This is being changed to be more consistent with Python's logging framework.
The `use_stdout` parameter has been left in for backwards-compatibility and does nothing.
@daanzu Hopefully this makes the temporary fix added by #235 work properly if `setup_log()` is used instead of `logging.basicConfig()`.

Change the setup_log() function to output log messages to stderr

---

dragonfly/actions/keyboard/_x11_xdotool.py

CC @tbenst, @shervinemami.
This makes Dragonfly's Key and Text action classes type keys much faster on X11.
This does not affect key event delays defined in action specs (e.g. `Key("shift:down/3, down/3, shift:up/3")`). In fact, these delays should be more precise with these changes.

Change the XdotoolKeyboard class to use '--delay 0' for typing keys

---

documentation/language.txt

I've made some improvements to Dragonfly's documentation for spoken language support:
- Supported languages for Dragon 15, WSR and CMU Pocket Sphinx are now listed on the page. I have put asterisks next to the spoken languages I have successfully tested with WSR and Sphinx.
- Languages with built-in grammar support (e.g. for `IntegerRef`) are listed separately.
- Sample code at the top for printing the engine language.
- A few other useful notes.
@daanzu I wasn't sure about spoken languages supported by the Kaldi engine backend. Let me know what should be listed in this section.

Improve Dragonfly's documentation for spoken language support

---

dragonfly/engines/__init__.py

Might cause dramas if someone relies on this feature. But I assume this is useful for nearly everyone, since it gives an error instead of silently ignoring custom args.
Protects from silent issues such as this:
```
get_current_engine('kaldi').print_mic_list()
engine = get_engine("kaldi", vad_aggressiveness=2)
```
(where the user will think their custom setting is being used, but actually the default settings are being used)

Raise an error if args were passed to get_engine() but silently ignored.

---

dragonfly/engines/backend_sphinx/engine.py

Closes #23.
The engine attempts to use the language model hypothesis to decode dictation-only specs if no grammar rule matched. This allows using free-dictation with Pocket Sphinx, but not in any required combination with other Dragonfly elements in the same rule.

Make Dictation-only rules work with the Sphinx engine again

---

documentation/grammar.txt
dragonfly/engines/backend_kaldi/engine.py
dragonfly/engines/backend_natlink/engine.py
dragonfly/engines/backend_natlink/recobs.py
dragonfly/engines/backend_sapi5/engine.py
dragonfly/engines/backend_sapi5/recobs.py
dragonfly/engines/backend_sphinx/engine.py
dragonfly/engines/backend_sphinx/grammar_wrapper.py
dragonfly/engines/backend_text/engine.py
dragonfly/engines/base/__init__.py
dragonfly/engines/base/grammar_wrapper.py
dragonfly/engines/base/recobs.py
dragonfly/grammar/recobs.py
dragonfly/grammar/recobs_callbacks.py

This PR exposes internal engine results objects via grammar callbacks. This allows the following custom `Grammar` class to work:
```Python
class MyGrammar(Grammar):
def process_recognition(self, words, results):
print("process_recognition()")
print(words)
print(results)
return True  
def process_recognition_other(self, words, results):
print("process_recognition_other()")
print(words)
print(results)
def process_recognition_failure(self, results):
print("process_recognition_failure()")
print(results)
```
I have implemented and tested this for WSR/SAPI 5. I will add the requested Natlink implementation before merging. For consistency, I'd like to also have something implemented for the CMU Pocket Sphinx engine.
I've also updated the documentation section on `Grammar` recognition callbacks. …

Expose internal engine results objects via grammar callbacks

---

dragonfly/__init__.py
dragonfly/test/suites.py
dragonfly/test/test_clipboard.py
dragonfly/windows/clipboard.py

Dragonfly was changed to use a cross-platform clipboard class a while ago. This simply changes the default Clipboard class to the original Win32 Clipboard class on Windows, as it supports more clipboard formats than the cross-platform class.
This change is backwards-compatible; both classes have the same methods and the cross-platform class was based on the Win32 class.

Use Dragonfly's Win32 Clipboard class on Windows

---

documentation/elements.txt
documentation/test_grammar_elements_basic_doctest.txt
dragonfly/engines/backend_kaldi/engine.py
dragonfly/engines/backend_natlink/compiler.py
dragonfly/engines/backend_natlink/engine.py
dragonfly/engines/backend_sapi5/engine.py
dragonfly/engines/backend_sphinx/engine.py
dragonfly/engines/backend_text/engine.py
dragonfly/engines/base/engine.py
dragonfly/grammar/elements_basic.py
dragonfly/grammar/state.py

Closes #138.
As discussed in #138, use of quoted words can improve accuracy in some cases. This PR allows quoted words to be used in `Literal` elements, which in turn allows them to be used in `Compound` and `Choice` elements as well as in `MappingRule` and `CompoundRule` spec strings.
Only the Natlink engine back-end currently supports them completely. If quoted words are used with other engine back-ends, quoting is effectively ignored. I have added a `quoted_words_support` engine property for checking if the current engine can compile and recognize quoted words.
Using quoted strings with DNS/Natlink may in fact *decrease* recognition accuracy for certain phrases. I think this depends on the current DNS vocabulary.
```Python
from dragonfly import Literal, CompoundRule, MappingRule, Text …
```

Add support for quoted words in rules

---

dragonfly/engines/backend_natlink/engine.py

This method should only close the waitForSpeech() window associated with the current process, if there is one.

Fix bug in the NatlinkEngine.disconnect() method

---

dragonfly/engines/backend_natlink/engine.py

This fixes an issue where some words in utterances are reported with a suffix such as "I\pronoun" instead of "I", such that they are not matched when resolving the command. This is easily reproducible because you will not be able to execute a command with the word "I" in it. Simply stripping this suffix resolves the problem. I've been using this change locally for a while and it hasn't caused any trouble.

Fix bug where some words cannot be used in grammars

---

dragonfly/__main__.py

The *files* argument used by both the 'test' and 'load' commands will now show an error message if a glob pattern didn't match any file.
@LexiconCode Thanks for letting me know about this :)

Fix CLI error reporting and file pattern matching issues

---

documentation/clipboard.txt
dragonfly/windows/clipboard.py

The class now polls for clipboard access for up to 500 ms. The polling is necessary because the clipboard is a shared resource which may be in use by another process. If the clipboard could not be accessed after 500 ms, then an error will be raised. I have exposed and documented the `win32_clipboard_ctx` context manager function that does this, in case that's useful for anyone.
As the cross-platform `Clipboard` class already does this via pyperclip, this fixes a regression introduced in version 0.24.0 by using the old Windows `Clipboard` class on Windows.

Change the Windows Clipboard class to poll for clipboard access

---

dragonfly/windows/win32_window.py

Re: #213, #265.
This changes the method to properly check if the control key is already held down.

Fix bug causing Win32Window.set_foreground() to fail sometimes

---

dragonfly/engines/backend_natlink/engine.py

Reverts dictation-toolbox/dragonfly#261
Sorry @wolfmanstout, the changes in #261 were breaking a few things. Using "I\pronoun" instead of "I" in commands seems to work just fine for me. Perhaps there should be hooks for these sort of changes.

Revert "Fix bug where some words cannot be used in grammars"

---

documentation/faq.txt
dragonfly/engines/backend_natlink/engine.py

Re: #242.
This changes the Natlink engine to retry grammar rule decoding and recognition processing with non-grammar words set as dictation words instead.
This partial fix makes it possible to match dictation for all words except those in the current grammar. Fixing this issue completely would be quite difficult and time-consuming. Since it only occurs in some versions of Dragon, I think this fix should be sufficient. It would not be difficult to work around limitations by using a dedicated grammar for speaking command words in other grammars.

Add partial fix for dictation-related DNS recognition failures

---

dragonfly/engines/backend_kaldi/engine.py
dragonfly/engines/backend_sphinx/engine.py
dragonfly/engines/backend_sphinx/grammar_wrapper.py

This changes both engine back-ends to only get window attributes once per utterance. This change should reduce delays on macOS.
@daanzu This is the change I mentioned on Gitter. Sorry I didn't properly optimize the Sphinx engine code you ended up using in Kaldi!

Optimize Kaldi & Sphinx window attribute checks on phrase start

---

dragonfly/engines/__init__.py

- Stop overriding the internal `_default_engine` variable by deferring to the `register_engine_init()` method.
- Fix two code style issues (long lines).
- Fix valid names check.

Fix issues with the get_engine() function

---

dragonfly/language/en/short_number.py
dragonfly/test/test_language_en_number.py

Fairly simple fix to add the high numbers, which will pretty much emulate the behaviour of IntegerRef.

Add high numbers to ShortIntegerRef

---

README.rst
documentation/faq.txt
documentation/installation.txt
documentation/kaldi_engine.txt
dragonfly/windows/x11_window.py

The ``wmctrl`` program is now used to adjust the [Extended Window Manager Hints](https://specifications.freedesktop.org/wm-spec/latest/) (EWMH) for window maximization in most X11 window managers. This is better than using a keyboard shortcut. The documentation has been updated to recommend installing both ``wmctrl`` and ``xdotool`` when using Dragonfly on Linux in an X11 session.
It should be noted that neither the current ``xdotool`` or ``xprop`` release versions can maximize the window by EWMH, so the new external dependency is necessary.

Change X11Window.maximize() method to use maximization hints

---

dragonfly/windows/x11_monitor.py

- Monitor rectangles are now initialised using the correct dx and dy values.
- The monitor with top left X coordinate 0 is considered the primary monitor instead of the monitor with coordinates (0,0).
This fixes the `Window.get_containing_monitor()` method on X11 for multi-monitor setups.

Fix two bugs with the X11Monitor class

---

dragonfly/grammar/grammar_base.py
dragonfly/grammar/rule_base.py

This makes it possible to adjust contexts of grammars and rules after they have been instantiated.
Questions to be answered before merging:
* Are there any potential side effects? For example, could it occur that a context change happens during `process_recognition`?

Allow changing rules' and grammars' contexts after instantiation

---

documentation/faq.txt
dragonfly/windows/win32_monitor.py

Closes #289.
This is @wolfmanstout's patch (https://github.com/dictation-toolbox/dragonfly/commit/c3a1b1e306a720e5b2e1ad3b8c5c3d4e1e30c668) with a safety check for older versions of Windows, plus some logging if setting the process DPI awareness fails (`E_INVALIDARG` and `E_ACCESSDENIED` are handled). I have also updated the relevant FAQ added in 4e5f0a9.
Microsoft's documentation indicates that the Windows 10 [`SetProcessDpiAwarenessContext()`](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setprocessdpiawarenesscontext) function is recommended instead of `SetProcessDpiAwareness()` in situations where the DPI awareness cannot be set in the application manifest. I don't understand how to use that function though, so this will do.
@LexiconCode Regarding the issues …

Set DPI awareness automatically when dragonfly is imported

---

dragonfly/test/rule_testcase.py
dragonfly/test/test_contexts.py
dragonfly/test/test_engine_kaldi.py
dragonfly/test/test_engine_natlink.py
dragonfly/test/test_engine_text.py
dragonfly/test/test_rpc.py
dragonfly/test/test_timer.py

This PR introduces a few changes to Dragonfly's test suite, most notably removing unnecessary calls to `engine.connect()` and `engine.disconnect()`, which only need to be called at the start and the end of the test suite respectively. I still need to fix some problems before merging.
@daanzu This seems to have fixed the memory leak issues with Kaldi I mentioned somewhere. I tested with KaldiAG version 1.8.0.

Test suite changes

---

dragonfly/engines/backend_kaldi/audio.py
dragonfly/engines/backend_kaldi/engine.py
dragonfly/test/test_engine_kaldi.py

@LexiconCode Curious if this reduces spurious messages with disconnect.

Minor Kaldi updates

---

documentation/test_word_formatting_v11_doctest.txt
dragonfly/engines/backend_natlink/dictation_format.py

Fixes #311.
This bug causes formatting to be applied to regular spoken words
that happen to match DNS word properties, but were not provided in
written\property\spoken form by DNS.
One example of this is the spoken word "point", which can be
written as "." or "point".

Fix DNS dictation bug where formatting can be applied incorrectly

---

dragonfly/engines/backend_kaldi/engine.py

CC @daanzu
I noticed this bug when running the test suite. This PR adds two missing `notify_failure()` calls.

Fix recognition observer bug with the KaldiEngine.mimic() method

---

dragonfly/examples/_functions_example.py

This command module shows how to use Dragonfly's Function action to call Python functions with the values associated with spoken Choice, Dictation and IntegerRef elements.
The module requires the 'geocoder' Python package and was initially written by @LexiconCode.

Add _functions_example.py example command module

---

dragonfly/actions/keyboard/_base.py

I'm running i3wm on Arch Linux. XDG_SESSION_TYPE was set to "tty" despite running X11. It took me quite some time to figure out what was going on, so I wanted to make it easier for anyone encountering the same problem.

Improve error message when X11 can't be detected

---

dragonfly/language/base/integer.py
dragonfly/language/base/integer_internal.py
dragonfly/language/de/number.py
dragonfly/test/test_language_de_number.py

Closes #306.
This PR adjusts the German language integer implementation so that integers between 20 and 99 can be spoken either as one word or multiple words, e.g. 'ein und zwanzig' and 'einundzwanzig' for the integer 21. This also fixes the problem when speaking larger numbers that include these words.
The changes to the internal integer classes may be useful in other language implementations. Before merging, I will add extra functionality for only using what I have called "modified paths". This will allow, to use my above example, recognizing 'einundzwanzig', but not 'ein und zwanzig'. I don't think this should be enabled for German language integers, however.
@tripfish If you get a chance, could you give this branch a try and let me know if there are issues? It seems to be working with …

Change German integer impl. to support compound words in range 20-99

---

dragonfly/util/clipboard.py
dragonfly/windows/clipboard.py

Fixes a bug where the clipboard does not properly handle 'None'
```
>>> import dragonfly.util.clipboard
>>> clip = dragonfly.util.clipboard.Clipboard()
>>> clip.has_text()
False
>>> clip.set_text('None')
>>> clip.has_text()
True
>>> clip.get_text()
'None'
>>> clip.set_text(None)
>>> clip.has_text()
False
>>> clip.get_text()
>>> clip.set_text(False)
>>> clip.has_text()
True
>>> clip.get_text()
'False'
```
```
>>> import dragonfly.windows.clipboard
>>> clip2 = dragonfly.windows.clipboard.Clipboard()
>>> clip2.has_text()
False
>>> clip2.set_text('None')
>>> clip2.has_text()
True
>>> clip2.get_text()
'None'
>>> clip2.set_text(None)
>>> clip2.has_text()
False
>>> clip2.get_text()
>>> clip2.set_text(False)
>>> clip2.has_text()
True
>>> clip2.get_text()
'False'
```

Fix clipboard incorrect handling of None type

---

documentation/test_word_formatting_v11_doctest.txt
dragonfly/engines/backend_natlink/dictation_format.py

This aligns formatting with Dragon's dictation formatting. For example, try "X variable". Without this change, it is formatted as "Xvariable".

Fix incorrect dictation formatting for DNS letters

---

README.rst
documentation/clipboard.txt
documentation/installation.txt
documentation/kaldi_engine.txt
dragonfly/test/test_clipboard.py
dragonfly/windows/base_clipboard.py
dragonfly/windows/clipboard.py
dragonfly/windows/pyperclip_clipboard.py
dragonfly/windows/win32_clipboard.py
dragonfly/windows/x11_clipboard.py

This PR includes a number of improvements to Dragonfly's clipboard toolkit, mostly related to clipboard formats.
Re: #226.
* Adjust `BaseClipboard` class to handle the `CF_HDROP` clipboard format for copied files.
* Add abstract `BaseX11Clipboard` interface to the [X selections](https://specifications.freedesktop.org/clipboards-spec/clipboards-latest.txt).
* Add `XselClipboard` class for use on X11.
This class implements `BaseX11Clipboard` using the [`xsel`](http://www.vergenet.net/~conrad/software/xsel/) program and is now the default Clipboard class on X11. It supports all three X selections: PRIMARY, SECONDARY and CLIPBOARD. `CF_HDROP` content can be retrieved.
* Improve clipboard format support of the `PyperclipClipboard` class.
* `CF_HDROP` content can be retrieved on X11.
* Errors …

Clipboard toolkit improvements

---

dragonfly/engines/__init__.py

This makes the following changes to Dragonfly's `get_engine()` function:
- Change the function to return engine instances mainly at the end.
- Simplify some of the function's logic and add comments.
- Change the function to log messages instead of printing them.
- Change the function to log an info message for initialized engines (re: #330).
- Adjust order of preferred SR engine implementations: Kaldi is now preferred over SAPI 5 and Sphinx, if it is available (re: #330).
- Update the function documentation.

get_engine() function changes

---

dragonfly/actions/action_base_keyboard.py
dragonfly/actions/action_paste.py

This changes a few keyboard-related side-effects that occur when certain dragonfly modules are imported:
* Dragonfly's config file (~/.dragonfly2-speech/settings.cfg) for the Windows keyboard will now only be generated and/or loaded from on Windows and only the first time a keyboard action is used. The file and its parent directory will no longer be created on other platforms.
* Change the `Paste` action class to instantiate the default paste action (`Key`) in the constructor, if necessary, rather than when the module is imported.

Change keyboard-related import-time side-effects

---

documentation/elements.txt
documentation/object_model.txt
dragonfly/grammar/elements_compound.py

The Choice element may now be given a list or tuple of phrases to be recognised. The items must be strings and will be used as compound specs, same as with dictionary arguments. The returned values will be the recognised words.

Change the Choice element class to allow using list/tuple choices

---

dragonfly/actions/action_key.py
dragonfly/actions/action_paste.py
dragonfly/actions/action_text.py
dragonfly/actions/keyboard/_win32.py

This changes the Windows keyboard code to fallback on predefined virtual-key codes (see [this page](https://docs.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes)) for keys in ranges 0-9, a-z and A-Z if the key cannot be typed using the current keyboard layout.  This means that the equivalent key will be typed instead, allowing common keyboard shortcuts, such as Ctrl+C, to work properly.
If the Windows Unicode keyboard is enabled and keys in these ranges cannot be typed on the current keyboard layout, then Dragonfly will fallback on Unicode events. In such a scenario, pressing Ctrl+C using something like `Key("c-c")` would result in "c" being pressed without the Ctrl modifier key held down. This problem is documented in detail in the [documentation on …

Improve Windows keyboard action support for letter and number keys

---

dragonfly/actions/keyboard/_win32.py
dragonfly/actions/sendinput.py

This PR fixes a few bugs with the Windows keyboard input code and cleans it up a bit. The changes are as follows:
- Fix a Windows keyboard input bug related to letter and number keys.
- Change the `KeyboardInput` struct to only translate virtual keycodes to scan codes when necessary (in `__init__`).
- Remove the hardcoded "soft" keys set and defer to the Win32 `MapVirtualKey` / `MapVirtualKeyEx` function instead, which returns 0 for virtual keycodes that don't have corresponding scancodes.
- Fix Windows keyboard input bug related to scan codes.
The `KeyboardInput` struct in `sendinput.py` now falls back on the virtual-key code if there is no equivalent scan code available. This is not done if the virtual keycode is 0 (for `KEYEVENTF_UNICODE` mode).
These changes fix bugs that occur with …

Fix issues with the Windows keyboard input code

---

CODE_OF_CONDUCT.rst

CC @LexiconCode
This changes the project Code of Conduct, added in PR #260, to a new one based on [Angular's](https://github.com/angular/angular/blob/master/CODE_OF_CONDUCT.md). Attribution and a hyperlink to the original document are included at the end.
The new Code of Conduct is functionally the same, without language that, in my opinion, adds nothing and, in fact, somewhat explicitly conflates symptoms of larger societal issues with character flaws to be expunged from communities. It also seems to me that much of the language of the document that this PR replaces suggests that, if and when these problems arise, reasonable debate, e.g. the [Socratic method](https://en.wikipedia.org/wiki/Socratic_method), is always unlikely to yield results. I don't believe that these were the …

Change the project Code of Conduct

---

documentation/clipboard.txt
dragonfly/test/test_clipboard.py
dragonfly/windows/base_clipboard.py
dragonfly/windows/win32_clipboard.py

CC @LexiconCode
This PR adds a `Clipboard.wait_for_change()` method and makes `Clipboard` instances comparable.
The `wait_for_change()` method is a blocking method which returns whether or not the system clipboard changed within a specified timeout period.
On Windows, this method compares clipboard sequence numbers.  On other platforms, it compares the clipboard contents.  Both of these implementations use polling.
It might be helpful to have an optional `formats` argument for this method. That way you can poll for changes to specific clipboard formats.

Clipboard toolkit additions, improvements and bug fixes

---

README.rst
documentation/index.txt

The descriptions for both back-ends in the README and in the index of the documentation now read "open source and multi-platform".
@daanzu I think this is better. Does this look good to you?

Change introductory descriptions of Kaldi and Sphinx engines

---

CHANGELOG.rst
dragonfly/engines/backend_kaldi/engine.py

Re: #182.
This disables the logging workaround for a bug that has previously occurred on Windows using the Kaldi engine back-end.  I have reason to believe the bug no longer occurs, so the verbose debug logging can be disabled.
If I am mistaken in this, then the workaround may be enabled by calling the `KaldiEngine._apply_win32_kb_input_logging_fix()` method.

Disable Kaldi debug logging workaround for Windows Key action bug

---

dragonfly/actions/action_base_keyboard.py
dragonfly/actions/action_key.py
dragonfly/actions/action_text.py
dragonfly/actions/keyboard/__init__.py
dragonfly/actions/keyboard/_base.py
dragonfly/actions/keyboard/_pynput.py
dragonfly/actions/keyboard/_win32.py
dragonfly/actions/keyboard/_x11_base.py
dragonfly/actions/keyboard/_x11_libxdo.py
dragonfly/actions/keyboard/_x11_xdotool.py
dragonfly/actions/sendinput.py

This PR cleans up the keyboard code a little and fixes some bugs.
Summary:
- Change the Key and Text action classes to calculate keyboard
events at execution time instead of initialization time.
- Fix a regression with keyboard input actions on Windows.
This restores the list of extended keys removed from sendinput.py in PR 343.  If the specified virtual-key is in this list, e.g. the insert key, then the KEYEVENTF_EXTENDEDKEY flag is used.
- Fix a bug with Text action default pause values.
This change fixes a bug where the PAUSE_DEFAULT setting in the Windows-only settings.cfg file is not used properly by Text actions.
- Fix numerous code style issues.
- Remove doc build conditionals from keyboard/__init__.py.
These should be removed from other files too.  I plan to do that as part of a …

Cleanup keyboard code

---

README.rst
documentation/index.txt
documentation/kaldi_engine.txt

Re: #355.
Kaldi Active Grammar (KaldiAG) is licensed under the GNU Affero General Public License v3 (AGPL-3.0-or-later).  This has an effect on what Dragonfly can be used to do when used in conjunction with the Kaldi engine back-end.  These changes make this clearer in the docs.
@matthewmcintire @daanzu Do these changes look all right?

Make mention of AGPL v3 license and KaldiAG in the docs

---

documentation/kaldi_engine.txt
dragonfly/engines/backend_kaldi/compiler.py
dragonfly/engines/backend_kaldi/engine.py
setup.py

Updates to the latest `v3.0.0` of kaldi-active-grammar.
I updated some of the documentation, but @Danesprite might want to add more info to users about dependencies they may want to install. See https://github.com/daanzu/kaldi-active-grammar/blob/3b8961a64f34c0b03ce79559f5a8726c6f689618/README.md?plain=1#L92

Kaldi Update, including better local pronunciation generation

---

dragonfly/actions/action_mouse.py
dragonfly/actions/mouse/__init__.py
dragonfly/actions/mouse/_xdotool.py
setup.py

This PR adds a mouse implementation using xdotool and removes the requirement for pynput on Linux.
The only problem is that, unlike pynput, xdotool can emulate neither horizontal scrolling nor the "four" and "five" mouse buttons.  One way around this would be to try pynput first and use xdotool if it is unavailable.  Eventually, I would like to use python-xlib directly.

Add Xdotool mouse implementation

---

documentation/base_engine.txt
documentation/conf.py
documentation/engines.txt
dragonfly/__init__.py
dragonfly/engines/__init__.py
dragonfly/engines/backend_kaldi/engine.py
dragonfly/engines/backend_natlink/engine.py
dragonfly/engines/backend_natlink/speaker.py
dragonfly/engines/backend_sapi5/engine.py
dragonfly/engines/backend_sapi5/speaker.py
dragonfly/engines/backend_sphinx/engine.py
dragonfly/engines/backend_text/engine.py
dragonfly/engines/backend_text/speaker.py
dragonfly/engines/base/speaker.py
dragonfly/engines/base/speaker_stdin.py
dragonfly/log.py

The code has been moved into `Speaker` classes as part of an effort to allow more flexible use of the (limited) text-to-speech
functionality.  The `speak()` methods of these engine classes have been adjusted accordingly.
@comodoro This is a start on the decoupling of Dragonfly's text-to-speech functionality. We spoke about this on the dragonfly gitter channel a little while back.
I still have to adjust the base engine code to utilise SAPI 5 on Windows, if it is available. I will probably use a design similar to `get_engine()`. It would be nice to have a `Speaker` class that works on Linux, but that could be implemented later.
I would also like to add an option for asynchronous playback, similar to what the Windows [`PlaySound()`](https://docs.microsoft.com/en-us/previous-versions//dd743680 …

Make SR engine text-to-speech functionality more flexible

---

README.rst
pyproject.toml
python-publish.yml

python build command and editable installs.
Added the github action for building python packages. Updated the readme to provide instructions for the editable install and use of the build command. 
Note that even though the github action is provided, it will not be activated unless dragonfly admin sets it up and adds the dragonfly repository [to a trusted publisher](https://pypi.org/help/#trusted-publishers) on pypi.  This would let you publish from github using the release feature, instead of a local build, if desired.
The advantages of running the `python build` command is that build knows how to build a project, whether it is built with flit, setuptools, poetry, etc.  and it creates a virtual environment for the build, to help catch errors.   However, it is not required to use `build`, …

Support (but not require) build, editable installs, and github actions.

---

dragonfly/windows/win32_clipboard.py

Currently, when using the context manager, there's no indication if the clipboard timed out when waiting for a change.
This change makes it so I could write the following and be (mostly) certain my text made it to the clipboard:
```
with clipboard.synchronized_changes(timeout=2, raise_exception_on_timeout=True):
Key("c-c").execute()
```
This makes it simple to write rules that rely on getting the user's highlighted text and subsequently stop the action if not text was captured.

Optionally raise a timeout exception under context manager.

---

README.rst
documentation/index.txt
documentation/related_resources.txt

Add clearer gitter/matrix mention to README/documentation. Made documentation front page better match similar info from README. Fixed some missing double underscores for anonymous RST links.

Add clearer gitter/matrix mention to README/documentation; cleanup
